### ISSUE TITLE
An error occurred while executing the example : The signature verification failed: Error: pubKey must be 32 bytes long

### ISSUE THREAD

**Issue by nadongjun** [guggero/bip-schnorr#17]
Thanks for releasing the code.

https://github.com/guggero/bip-schnorr/blob/master/README.md#schnorr
I ran the example code in the Readme, but the following error occurred.
 
**"The signature verification failed: Error: pubKey must be 32 bytes long"**

How can I get rid of this error?

**Comment by guggero** [comment]
Thank you for the issue, I fixed the examples in the README.
