### ISSUE TITLE
Signature aggregation doesn't work reliably

### ISSUE THREAD

**Issue by guggero** [guggero/bip-schnorr#3]
Apparently the signature aggregation only works some times. The example works but some of the test cases don't, after passing the correct private keys instead of public keys...

**Comment by hbakhtiyor** [comment]
why not implemented batchverify? 
https://github.com/hbakhtiyor/schnorr/blob/batch-verify/schnorr.go#L93 mine is not working
what's maybe wrong?

**Comment by guggero** [comment]
Fixed by a723675fa4f4fbf832f55eba8040f4ac4318b14e
