### ISSUE TITLE
Schnorr Blinding

### ISSUE THREAD

**Issue by KevinKelbie** [guggero/bip-schnorr#5]
Hi, great work on this implementation of bip-schnorr. I was wondering if there is any plans to add Schnorr Blinding to this implementation or if you knew of any other libraries that does the same job and would work nicely with this library.

Thanks.

**Comment by guggero** [comment]
Thanks!

Do you mean something like this: https://conference.hitb.org/hitbsecconf2018dxb/materials/CLOSING%20KEYNOTE%20-%20Blind%20Digital%20Signatures%20-%20Dr%20Manar%20Abu%20Talib%20and%20Dr%20Qassim%20Nasir.pdf
(slide 58)?
It should be relatively easy to implement. But I have no idea when I have time to do so.

**Comment by KevinKelbie** [comment]
I'll be honest, I'm not savvy with the cryptography. The reason I asked for Schnorr Blind Signatures is that I am implementing Statechains which utilize schnorr and will require messages to be blinded before signing them.

The Schnorr Bip does [briefly go over blind signatures](https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki#blind-signatures) but it doesn't say much.

If you believe its beyond the scope of this library then thats fine :)

**Comment by guggero** [comment]
I started working on the math but I never had the time to implement it. Will probably take some more time but the topic seems to fit this library, I think.

**Comment by KevinKelbie** [comment]
That's awesome! Ping me once you have an initial implementation working and I'll happily start using it and let you know if there are any bugs.

**Comment by KevinKelbie** [comment]
Any update on this? I know this is not your full-time job so I'm grateful you are looking into this at all.

**Comment by guggero** [comment]
I spoke to someone at Blockstream and apparently there is a rogue-key-attack known to affect the most straight-forward way I would have implemented blind signatures (similar to what they had to fix in MuSig over naïve Schnorr multisignature). So the signature protocol would probably look a bit more complicated.
But to be honest, I'm not a cryptography researcher and don't have the experience to figure out the protocol by myself. Or at least it probably wouldn't be secure.
So I'm sorry, I have to shelve this until there is a secure implementation out there that I could port to JS.
