### ISSUE TITLE
Combined private key

### ISSUE THREAD

**Issue by jorisoudejans** [guggero/bip-schnorr#6]
Would it be possible to get a combined private key given all private keys?

**Comment by guggero** [comment]
For the naïve key aggregation it's pretty easy. You just add up all the private keys.
So `(k_0 + k_1 + ... k_i) mod n` where `n` is the curve order.

Example:
```
const BigInteger = require('bigi');
const ecurve = require('ecurve');
const curve = ecurve.getCurveByName('secp256k1');

const priv0 = BigInteger.fromHex('7e012f215c9425f08c7c8ea51747ff469e60ce8c698cfd8de282e099f317a651');
const pub0 = curve.G.multiply(priv0); // equal to 02a8ae1eeed4e532272093713e0dc26287d9fbd6d1259d370fc8d53aa523c15ad3

const priv1 = BigInteger.fromHex('13f3bf920c9fff0bed3b9b44309af95b79b78e221de91719f8130fcfcf8ed812');
const pub1 = curve.G.multiply(priv1); // equal to 02b05e375c6096da7564cfebda7334ae5f6f2745d2ace516364e21ab4eb22955c6

const privCombined = priv0.add(priv1).mod(curve.n);
const pubCombined = curve.G.multiply(privCombined); // equal to pub1.add(pub2)
```

For MuSig it's a bit more work. You would need to calculate the coefficient for every private key (`coefficient_i = H(L, pub_i)` where `L = H(pub_0, pub_1, ..., pub_i)`) and multiply it with that before adding them up.

**Comment by jorisoudejans** [comment]
Thank you for your answer! I've been trying to implement your suggestion (for MuSig I mean), and I was looking at the `pubKeyCombine` function:

```
function pubKeyCombine(pubKeys, pubKeyHash) {
  const ell = pubKeyHash || computeEll(pubKeys);
  let X = null;
  for (let i = 0; i < pubKeys.length; i++) {
    const Xi = convert.pubKeyToPoint(pubKeys[i]);
    const coefficient = computeCoefficient(ell, i);
    const summand = Xi.multiply(coefficient);
    if (X === null) {
      X = summand;
    } else {
      X = X.add(summand);
    }
  }
  return convert.pointToBuffer(X);
}
```
Doesn't this function already do what you're suggesting, i.e. calculate the coefficient (`const coefficient = computeCoefficient(ell, i)`), and sum the factors of the coefficients with the private keys? Only difference would be to use `privKeys` instead of `pubKeys`.

Furthermore, when looking at the [MuSig paper](https://eprint.iacr.org/2018/068.pdf), it seems that the aggregated public key is a multiplication of public keys raised to the coefficient (page 4). Why does `pubKeyCombine` work then?

Anyway, great work on this library!

**Comment by jorisoudejans** [comment]
Hi, I'm still trying to implement your MuSig suggestion, this is what I have:
```
function privKeyCombine (privKeys, pubKeys, ell) {
  let X = null
  for (let i = 0; i < privKeys.length; i++) {
    const Xi = privKeys[i]
    const coefficient = convert.bufferToInt(convert.hash(Buffer.concat([ell, pubKeys[i]])))
    const summand = Xi.multiply(coefficient)
    if (X === null) {
      X = summand.mod(curve.n)
    } else {
      X = X.add(summand).mod(curve.n)
    }
  }
  return X
}
```
However, this does not give the right private key. Could you perhaps advise me what I'm doing incorrectly? I've been stuck on this for a while now.

**Comment by guggero** [comment]
Hi

You need to use the same coefficient for the `privKeyCombine` as well as for `pubKeyCombine`, otherwise they won't correspond.
I know that `computeCoefficient()` is not exposed. So you might need to copy this from the source to get it working. But the rest of your code looks correct so far.
May I ask what exactly you are trying to achieve? Just out of curiosity.

Concerning your question about notation. Because it's math on a closed group, there are just two basic operations. And sometimes they are written as plus and times while in other papers the times and raise operations are used.

**Comment by jorisoudejans** [comment]
Hi, thanks for the explanation, I actually just got it to work with the same coefficient:
```
const privCombined = priv0.multiply(convert.bufferToInt(hash(L, pubKeys[0])))
  .add(priv1.multiply(convert.bufferToInt(hash(L, pubKeys[1])))).mod(curve.n)
const pubDirect = curve.G.multiply(privCombined)
const x = convert.pubKeyToPoint(pubKeys[0]).multiply(convert.bufferToInt(hash(L, pubKeys[0])))
  .add(convert.pubKeyToPoint(pubKeys[1]).multiply(convert.bufferToInt(hash(L, pubKeys[1]))))
const pubCombined = x
console.log('Musig from priv          ', convert.pointToBuffer(pubDirect).toString('hex'))
console.log('Musig pub                ', convert.pointToBuffer(pubCombined).toString('hex'))
```
I'm trying to generate a private/public key-pair where the private key is shared between multiple parties and the public key is used as a crypto-address to send funds to.
