### ISSUE TITLE
Schnorr and MuSign multi sig m out of n signatures?

### ISSUE THREAD

**Issue by ibudisteanu** [guggero/bip-schnorr#9]
Hi! Awesome work! I was wondering how do you get a multsig of m out of n, let's suppose, m is 2 and n is 3. So, I am interested to generate a multsig of 2 of 3 ? Any hints or any example that could help me out to understand how to do a 2 out of 3 multsig ? Thanks

**Comment by guggero** [comment]
Hi @ibudisteanu, thanks!
What you are describing is what's called a threshold signature. I did start a branch for that (https://github.com/guggero/bip-schnorr/tree/threshold-signatures) but then I noticed that even Blockstream hadn't decided on how to implement them yet (maybe they did now?). That's why I stopped working on that.
To answer your question: It's currently not possible, only n-of-n multisig is implemented.

**Comment by ibudisteanu** [comment]
Thanks for the reply. I didn't know about this issue. Now, it makes a lot of sense. The resulting point from the aggregation ( pub keys and private keys) is an independent valid point of the elliptic curve. This is why MuSig by default it supports only n-of-n multisig. 

I see that one approach is to use Merkle Multisig chapter 4 https://medium.com/cryptoadvance/how-schnorr-signatures-may-improve-bitcoin-91655bcb4744

**Comment by ibudisteanu** [comment]
It looks like BLS signatures allow fast signature verification, aggregation and multisg m of n. Did you try to use BLS signatures ?

**Comment by sarvalabs-sai** [comment]
NO @ibudisteanu,  BLS signature verification is slower than Schnorr's and even slower while verifying aggregated signature

**Comment by sarvalabs-sai** [comment]
The curve suggests it will, not sure about this library implementation

**Comment by uc-Pri** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
IvanEh, @Klesas, @alexbudin, @pgrekovich, @Tmarty, @VartelK, @Fadingvision, @Jstakhanov, @baoanh1310, @chunyenHuang, @kashifali554, @BoomLEE, @hubingliang, @ahm3dkira, @webgurucan, @juanitoddd, @gnujoow, @phil9987, @EliasGabrielsson, @potterdai
